env: 'dev'
# first create the database with the command:
# CREATE DATABASE student_db;
# before running the application for postgres
storage_path: 'postgres://postgres:password@localhost:5432/student_db?sslmode=disable'
http_server:
  address: 'localhost:8082'
